#!/usr/bin/env python3
"""
CosmicForge Lab - Tarea VASP
Generación de archivos de entrada para simulación VASP

Archivos generados:
- POSCAR: Estructura cristalina
- INCAR: Parámetros de cálculo  
- KPOINTS: Malla de puntos k
- POTCAR: Referencia

Ejemplo de uso:
    from tasks.task_vasp import VASPTask
    
    task = VASPTask(metal="Ti", physical_props={"density": 4.5})
    files = task.generate_all()
    task.save_files(output_dir="./vasp_calculation")
"""

import os
from pathlib import Path
from typing import Dict, Optional

class VASPTask:
    """Genera archivos de entrada para cálculos VASP."""
    
    LATTICE_PARAMS = {
        "Ti": {"a": 4.594, "b": 4.594, "c": 2.959},
        "Al": {"a": 4.760, "b": 4.760, "c": 12.99},
        "Fe": {"a": 5.035, "b": 5.035, "c": 13.72},
        "Zn": {"a": 3.250, "b": 3.250, "c": 5.207},
        "Cu": {"a": 4.697, "b": 4.697, "c": 3.422},
        "Ni": {"a": 4.177, "b": 4.177, "c": 4.177},
        "Co": {"a": 4.220, "b": 4.220, "c": 4.220},
        "Mn": {"a": 4.444, "b": 4.444, "c": 4.444},
        "Cr": {"a": 4.160, "b": 4.160, "c": 4.160},
        "Mo": {"a": 4.780, "b": 4.780, "c": 4.780},
        "W": {"a": 4.580, "b": 4.580, "c": 4.580},
        "Ag": {"a": 4.086, "b": 4.086, "c": 4.086},
        "Au": {"a": 4.078, "b": 4.078, "c": 4.078},
        "Pt": {"a": 3.923, "b": 3.923, "c": 3.923},
        "Pd": {"a": 3.890, "b": 3.890, "c": 3.890},
    }
    
    INCAR_TEMPLATES = {
        "scf": {
            "SYSTEM": "Material calculado con CosmicForge Lab",
            "ENCUT": 520, "EDIFF": 1.0e-6, "IBRION": -1,
            "ISMEAR": 0, "SIGMA": 0.05, "PREC": "Accurate",
        },
        "relax": {
            "SYSTEM": "Relajación estructural",
            "ENCUT": 520, "EDIFF": 1.0e-6, "EDIFFG": -0.01,
            "IBRION": 2, "ISIF": 3, "NSW": 100,
            "ISMEAR": 0, "SIGMA": 0.05, "PREC": "Accurate",
        },
        "bands": {
            "SYSTEM": "Estructura de bandas",
            "ENCUT": 520, "EDIFF": 1.0e-6, "IBRION": -1,
            "ISMEAR": 0, "SIGMA": 0.05, "ICHARG": 11, "LORBIT": 11,
        },
        "md": {
            "SYSTEM": "Dinámica molecular",
            "ENCUT": 400, "EDIFF": 1.0e-4, "IBRION": 0,
            "NSW": 10000, "POTIM": 1.0, "SMASS": -3,
            "ISMEAR": 0, "SIGMA": 0.1,
        }
    }
    
    def __init__(self, metal: str, physical_props: Optional[Dict] = None, calc_type: str = "scf"):
        self.metal = metal.capitalize() if len(metal) == 2 else metal.upper()
        self.physical_props = physical_props or {}
        self.calc_type = calc_type
        self.lattice = self.LATTICE_PARAMS.get(self.metal, {"a": 4.5, "b": 4.5, "c": 3.0})
    
    def generate_poscar(self, scale_factor: float = 1.0) -> str:
        """Genera el archivo POSCAR."""
        a = self.lattice["a"] * scale_factor
        b = self.lattice["b"] * scale_factor
        c = self.lattice["c"] * scale_factor
        
        return f"""{self.metal}O2 - Generated by CosmicForge Lab
{scale_factor:.1f}
   {a:.6f}  0.000000  0.000000
   0.000000  {b:.6f}  0.000000
   0.000000  0.000000  {c:.6f}
{self.metal}   O
 1   2
Direct
  0.000000  0.000000  0.000000  {self.metal}
  0.304961  0.304961  0.000000  O
 -0.304961 -0.304961  0.000000  O
"""
    
    def generate_incar(self, custom_params: Optional[Dict] = None) -> str:
        """Genera el archivo INCAR."""
        params = self.INCAR_TEMPLATES.get(self.calc_type, self.INCAR_TEMPLATES["scf"]).copy()
        if custom_params:
            params.update(custom_params)
        
        lines = [f"# INCAR - CosmicForge Lab", f"# Cálculo: {self.calc_type.upper()}", ""]
        for key, value in params.items():
            if isinstance(value, bool):
                value = ".TRUE." if value else ".FALSE."
            lines.append(f"{key} = {value}")
        return "\n".join(lines)
    
    def generate_kpoints(self, mesh: tuple = (8, 8, 8)) -> str:
        """Genera el archivo KPOINTS."""
        nx, ny, nz = mesh
        return f"""K-Points - CosmicForge Lab
0
Monkhorst-Pack
{nx} {ny} {nz}
0 0 0
"""
    
    def generate_kpoints_bands(self, n_points: int = 20) -> str:
        """Genera KPOINTS para estructura de bandas."""
        return f"""K-Points for bands
10
Line-mode
Reciprocal
  0.000  0.000  0.000    {n_points}  ! Gamma
  0.500  0.000  0.000    {n_points}  ! X
  0.500  0.500  0.000    {n_points}  ! M
  0.000  0.500  0.000    {n_points}  ! Y
  0.000  0.000  0.000    {n_points}  ! Gamma
  0.000  0.000  0.500    {n_points}  ! Z
"""
    
    def generate_potcar_info(self) -> str:
        """Información para obtener POTCAR."""
        return f"""# POTCAR Info - VASP requiere licencia
# Para {self.metal}O2 combina:
# cat $VASP_PP_PATH/{self.metal}/POTCAR $VASP_PP_PATH/O/POTCAR > POTCAR
# Recomendado: PAW_{self.metal}_pv para incluir semicore
"""
    
    def generate_all(self) -> Dict[str, str]:
        """Genera todos los archivos."""
        files = {
            "POSCAR": self.generate_poscar(),
            "INCAR": self.generate_incar(),
            "KPOINTS": self.generate_kpoints(),
            "POTCAR_README.txt": self.generate_potcar_info()
        }
        if self.calc_type == "bands":
            files["KPOINTS"] = self.generate_kpoints_bands()
        return files
    
    def save_files(self, output_dir: str = "./vasp_calc") -> None:
        """Guarda todos los archivos."""
        Path(output_dir).mkdir(parents=True, exist_ok=True)
        for filename, content in self.generate_all().items():
            with open(f"{output_dir}/{filename}", "w") as f:
                f.write(content)
        print(f"✓ Archivos guardados en {output_dir}/")


# EJEMPLO DE USO
if __name__ == "__main__":
    print("=" * 50)
    print("CosmicForge Lab - VASP Task Example")
    print("=" * 50)
    
    # Crear tarea VASP
    task = VASPTask(metal="Ti", calc_type="scf")
    
    # Mostrar archivos
    print("\n--- POSCAR ---")
    print(task.generate_poscar())
    
    print("\n--- INCAR ---")
    print(task.generate_incar())
    
    print("\n--- KPOINTS ---")
    print(task.generate_kpoints())
    
    # Guardar archivos
    # task.save_files("./vasp_TiO2")
